spring:
  datasource:
    url: jdbc:mysql://localhost:3306/staffjoy_account?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    show-sql: true
server:
  port: 8082
  servlet:
    context-path: /feign
staffjoy:
  account-service-endpoint: http://localhost:8081
management:
  endpoints:
    web:
      exposure:
        include: "*"
